const PRODUCT_LOADING = "PRODUCT_LOADING";
const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
const PRODUCT_ERROR = "PRODUCT_ERROR";
const PRODUCT_STATUS_UPDATE = "PRODUCT_STATUS_UPDATE";

export { PRODUCT_ERROR, PRODUCT_LOADING, PRODUCT_SUCCESS,PRODUCT_STATUS_UPDATE };